---
name: make tests and lint

on: [push, pull_request]

jobs:
  makeTestsLint:
    runs-on: ubuntu-latest
    name: Make Tests and Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install coverage
        run: sudo apt-get install python-coverage

      - name: make tests
        run: make tests-debian

      - name: make lint
        run: make lint
