---
name: make tests and lint

on: [push, pull_request]

jobs:
  makeTestsLint:
    runs-on: ubuntu-latest
    name: Make Tests and Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v1
        with: 
          python-version: '3.7'

      - name: install coverage
        run: sudo apt-get install python3-coverage python3-pytest python3-configargparse pylint3

      - name: make tests
        run: make tests-debian

      - name: make lint
        run: make lint-debian
